### ISSUE TITLE
Multiple job selection / Delete all jobs

### ISSUE THREAD

**Issue by jodator** [benderjs/benderjs#119]
It would be nice to select multiple jobs and perform some action - mostly do delete them all.

Maybe perform all would be usable also - but I just need to delete all jobs.

The main problem is:
- create job to collect code coverage
- write new test
- create another job to collect code coverage with new test

**Comment by gregpabian** [comment]
Server side is ready for the feature thanks to 7c38867c43850751af5885307e2b7b6209d219c3, now it's just a matter of modifying the dashboard.
