### ISSUE TITLE
Deferring management by callbacks

### ISSUE THREAD

**Issue by mlewand** [benderjs/benderjs#141]
We need a better method to defer bender start.

Currently there's only `bender.deferred` property.

More flexible approach would be exposing a method like:

```javascript
var lock1 = bender.deferTest();
var lock2 = bender.deferTest();

// Tests are not ran at this point, because deferring functions were created.
bender.test( testsObject );

// do some initialization stuff...
lock1(); // After this call tests are still not ran.
lock2(); // This is the last remaining lock, so tests are ran.
```

So basically we're asking for deferring in based on callbacks rather than single property.

After this change we'll need to put some work in CKEditor extension, to allow tests to load some extra stuff before tests are fired.

**Comment by gregpabian** [comment]
The support for `bender.defer()` is now shipped to the *dev* branch. The API works as we discussed:
```js
var unlock = bender.defer();

doSomeAsyncStuff(function () {
    // call unlock when done
    unlock();
});
```
This will defer the execution of `bender.start` method to the call of `unlock` function.

Additionally, I've also implemented a timeout which will be thrown when one of the deferred callbacks fails. You can set it up in bender.js config file using `defermentTimeout` option (not sure about the name, maybe `testDefermentTimeout` would sound better?), at the moment it defaults to 5 seconds (not sure about this too).

I've also modified several plugins that require asynchronous initialization, e.g. `benderjs-amd` and `benderjs-chai`, to utilize this API. You can check the result on their *dev* branches. We still need to update the CKEditor plugin though.

If everything is fine, I'm gonna ship this feature in Bender 0.2.0.

**Comment by fredck** [comment]
It's a pity I didn't react so fast... we should have called it simply `deferTimeout`, IMHO.

**Comment by gregpabian** [comment]
We can always rename it in the 0.2.1 if it's a problem ;)

**Comment by gregpabian** [comment]
Actually, for me `deferTimeout` doesn't sound that good - "defer" is a verb and someone may think it's about "deferring a timeout" (which is wrong). I'd stay with the current form or something else that would express better what it really does.

**Comment by Reinmar** [comment]
I agree. I don't know what it does, but `defer` sounds better :D.
