### ISSUE TITLE
Allow custom error handling in tests

### ISSUE THREAD

**Issue by adelura** [benderjs/benderjs#144]
My use case is to write test which checks whether script which is loaded asynchmorously throw an exception. If this script throws then test should pass.

What I tried to do is to catch error:

```
window.addEventListener( 'error', function () {} );
```

But it doesn't help because bender catch error first and fail test. My second thought was to overwrite `bender.error` method and handle it on my way. Unfortunatelly original method is already bound to `error` listener.

----

In my opinion bender should have mechanism to default error handling. User should be allowed to define his or her custom function and decide whether default function should be called.

**Comment by gregpabian** [comment]
I'd still go with a simple solution like overriding `bender.error` with a custom function that eventually may call the original error handler. Besides using custom events will require adding EventEmitter implementation to the code which is loaded for every single test which may slow down things a bit and that's used just for a single scenario (at the moment)...
