### ISSUE TITLE
Memory leak on Firefox

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#154]
When I run all CKEditor tests (major branch, [df5a9dc](https://github.com/ckeditor/ckeditor-dev/commit/df5a9dc)),  on Firefox 34.0.5 on Windows 7 (32-bit), virtual machine, I get memory leak. Memory usage reach 1.5 GB and Firefox crash.

**Comment by gregpabian** [comment]
I can't reproduce this one with the latest master (447818b), could you please paste your VM configuration here?

**Comment by pjasiun** [comment]
It was "Skype Click to Call" plugin fault.

**Comment by gregpabian** [comment]
I was searching for a way to detect enabled extensions and unfortunately I couldn't find a good (universal) solution. Maybe we should consider adding a small notification shown at the top of the dashboard saying that using browser extensions while running tests may lead to a memory leak or even falsy results? Something like these information about the cookie policy...

**Comment by fredck** [comment]
That would be too intrusive. After all, not all extensions are bad. Other than the pain in the ass to always have to close this alert (for example when having vms with snapshots used for testing... like I have :)).

We don't have to workaround these issues. Showing a warning would be sufficient, so we may think about implementing checks for known extensions at least, if possible.
