### ISSUE TITLE
Bender 0.1.18 stopped generating test URLs for multiple jQuery versions

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#155]
I can find only the following tests in the dashboard:

* tests/adapters/jquery/events	Adapters	editor, unit, jquery	
* tests/adapters/jquery/form	Adapters	editor, unit, jquery	
* tests/adapters/jquery/instance	Adapters	editor, unit, jquery	
* tests/adapters/jquery/val	Adapters	editor, unit, jquery

**Comment by gregpabian** [comment]
What's your bender-jquery plugin version?

**Comment by Reinmar** [comment]
Too old it turned out. 0.2.2. After upgrading to 0.2.3 it works fine.
