### ISSUE TITLE
It is not possible to override template's doctype in a test file

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#159]
I defined a manual test file starting with:

```
<!DOCTYPE html PUBLIC>
```

Hoping to trigger quirks mode. Unfortunately Bender still prints the standards doctype.

**Comment by adelura** [comment]
We already talked about this with @gregpabian. Removing doctype will put bender into quirks, but bender doesn't work in this mode :D

**Comment by gregpabian** [comment]
Actually it does work. I've just tried forcing quirks with `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">` and it runs (more-less).

**Comment by Reinmar** [comment]
I don't expect the automated tests to work (they wouldn't pass anyway), but at least the manual should work.

It would be actually good if we could set a doctype when starting/configuring Bender. Then we could run all manual tests on QM easily.

**Comment by gregpabian** [comment]
So you'd like to set the doctype on server configuration level, i.e. in `bender.js` configuration file?

**Comment by gregpabian** [comment]
I'm closing this one for several reasons:

- You CAN override the DocType. If you need quirks, use:
  ```
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
  ```
- If you still think you should be able to put anything in the DocType an it should be accepted, please create a ticket for that in [dom-combiner's repository](https://github.com/benderjs/dom-combiner), not here.

- > It would be actually good if we could set the doctype when starting/configuring Bender. Then we could run all manual tests on QM easily.

  If you still think this is a valuable feature, please open another ticket for that with further explanations on how it should work.
