### ISSUE TITLE
Change command used to get version

### ISSUE THREAD

**Issue by mlewand** [benderjs/benderjs#162]
Right now to get Bender version we need to input:

```
bender version
```

I face it all the time that I'm using `bender --version` instead, just because it's more common (I feel like).

eg.
```
node --version
npm --version
python3 --version
ruby --version
git --version # (though it supports `git version` too)
phantomjs --version
```

In addition to that we could add support for `-v` abbreviation.

**Comment by gregpabian** [comment]
Agreed, I just followed the documentation I got when I was creating it ages ago ;)

**Comment by gregpabian** [comment]
I'll get it done once the ticket gregpabian/subcommander#5 is resolved.
