### ISSUE TITLE
[YUI][CKEditor] Automatic tests run before manual

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#164]
If manual test contains automatic part then automatic tests should run after manual. Instead, when I create YUI tests, they run before manual test and `Finish` button do nothing. I met this problem working on CKEditor ticket (http://dev.ckeditor.com/ticket/12805) so the issue may be in Bender Core, Bender YUI Plugin or Bender CKEditor Plugin. I am using Bender 0.2.1.

**Comment by gregpabian** [comment]
Just to summarize things: the fix for this issue required changes in the CKEditor plugin and benderjs-yui. The latter one is already published (version 0.2.4), I'm still waiting for someone to review my [ticket](https://dev.ckeditor.com/ticket/12935) for CKEditor and merge it to the major branch.

**Comment by Reinmar** [comment]
I'll review https://dev.ckeditor.com/ticket/12935.
