### ISSUE TITLE
Clean up after manual test

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#165]
I need to overwrite XHR object for the manual test and want to restore it when the test is done. There should be some way to clean up after manual tests. When https://github.com/benderjs/benderjs/issues/164 will be fixed I can use automatic test to do it, but maybe we should have a better solution. Creating a test which do nothing but a clean up is kind of hack. The most elegant would be a method: `bender.tearDown`, `bender.cleanUp` or `bender.manaulTestFinished`

**Comment by gregpabian** [comment]
PJ, do you still need this one? #164 is already fixed so you can do it that way for now. Could you please add more details? For example, a full test scenario would be helpful to understand what's the use case for this feature.

**Comment by pjasiun** [comment]
Yes. In many manual tests I need to change something: replace some methods to show error handling, change css (e.g. body style to test notification position) or mock external system (like XHR). In every such case some clean-up needs to be done when the test is finished and it would be very useful if I would have special method for this. At the moment I need to create special JS file only for clean-up. Also I make a mess in the *.html file, so it is strange that I clean it in the different file.

**Comment by gregpabian** [comment]
Feature is shipped on the `dev` branch. You can assign a cleanup function to `bender.tearDown` that will be called once the test is done, i.e. a user pressed "Done" button or the automatic tests finished.
