### ISSUE TITLE
Manual test description should be hideable

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#166]
I am not not able to test how element behave if it meet the left border of the viewport, because manual test description hides it. It should be possible to hide that description.

**Comment by scofalik** [comment]
For now I added a button that toggles manual description. It will be featured in next release. After a short discussion with @pjasiun we decided that it would be good to make an overhaul of manual tests UI. It would be useful to plugin in some kind of library for panels like manual description and console (see #137) and possibly other. An external plugin would take care of panel positioning, resizing and hiding.

I've made a new issue for this (#239).
