### ISSUE TITLE
bender run "freezes" in some specific scenarios with PhantomJS

### ISSUE THREAD

**Issue by gregpabian** [benderjs/benderjs#170]
I encountered this problem when running CKEditor5 tests on PhantomJS  using `bender run`.
When running any test from `ckeditor5-core`, the runner executes all the tests, but then for some reason it does not close the browser and stop the server.

**Comment by gregpabian** [comment]
After deeper investigation, the issue was caused by a module that tried to expose native Promises that are not available in PhantomJS at the moment. Still, an error should have been reported, but nothing happened.

**Comment by fredck** [comment]
Hum... this means that, as for now, CKEditor 5 is not compatible with PhantomJS.... that's sad :(

**Comment by gregpabian** [comment]
Yup, that's unfortunate, but we can temporarily use some polyfill for that.
Thankfully, there's already a related issue in PhantomJS repository: ariya/phantomjs#12401

**Comment by fredck** [comment]
We're appositely not including a polyfill in v5:
https://github.com/ckeditor/ckeditor5-design/wiki/Asynchrony-and-Promises#browser-compatibility

What about a bender plugin for this, which injects the polyfill when necessary?

**Comment by gregpabian** [comment]
> What about a bender plugin for this, which injects the polyfill when necessary?

You mean a check on the request level? So the polyfill is included only for some specific browsers, or it's always included, but applied only when necessary?

**Comment by fredck** [comment]
```
if ( typeof Promise == 'undefined' ) {
    // Inject the polyfill
}
```

It's a plugin that ensures that `Promise` is available, therefore we need a polyfill that matches the native implementation.

**Comment by gregpabian** [comment]
A plugin with ES6-style Promises polyfill was released, please see: https://github.com/benderjs/benderjs-promise
