### ISSUE TITLE
alert() should work in manual tests

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#172]
I see no reason why `alert` is not displayed in manual tests. Instead I get an error whenever testing application try to show alert.

**Comment by gregpabian** [comment]
Ask @Reinmar why, but IIRC it was his idea to use alerts this way.

**Comment by Reinmar** [comment]
In manual tests? I remember we talked about alerts, but I have no idea about what precisely. I see no reason why the manual part of manual test could not show an alert.

**Comment by gregpabian** [comment]
No, it wasn't about manual tests but alerts in general. And AFAIR alerts in CKTester also thrown errors instead of appearing, but again, I can't recall why...

**Comment by pjasiun** [comment]
In CKTester we did not have manual tests.

**Comment by Reinmar** [comment]
Yes. In automated tests alerts should throw. Simply because such alert is not desirable because it stops the tests execution. However, in manual tests it is not a problem.

**Comment by gregpabian** [comment]
K, I'm gonna re-enable them in manual tests only.

**Comment by adelura** [comment]
AFAIR we wanted to have some custom box visible somewhere in manual tests
which'll log information like alert has been executed and so on.
