### ISSUE TITLE
Unused applications should not be loaded

### ISSUE THREAD

**Issue by fredck** [benderjs/benderjs#176]
I have [included the following configurations in ckeditor5](https://github.com/ckeditor/ckeditor5/commit/d192057570ee50c759bccf1b83b2a2a7a96d6996):

```js
applications: {
	'ckeditor': {
		path: '.',
		files: [
			'node_modules/requirejs/require.js',
			'ckeditor.js'
		]
	},

	'ckeditor-build': {
		path: 'build',
		files: [
			'ckeditor.js'
		]
	}
},
```

Bender fails to start with the following error:

```
[31merror[39m: [applications] Path: "build" to "ckeditor-build" application does not exist.
```

There are no tests configured to use that application though, so it doesn't make much sense trying to load it at startup, am I wrong?

**Comment by gregpabian** [comment]
Having an application defined in a test group only means that all test pages created for this group will have the files specified in the application's files array included in test pages. But in some situations a test group may not have an application specified, yet still try to load some files from that application, so this configuration still has to be evaluated.

**Comment by fredck** [comment]
Ok, I'll have to figure out a different way to make it easy to run tests with the build version in ckeditor5 so. Thanks!
