### ISSUE TITLE
Browsers in table headers are sorted wrong.

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#178]
1. create a job with IE 8 and IE 11.
2. run IE 8.
3. press "capture the browser" button.

Result: on the dashboard I see IE 11 tests running instead of IE 8.

**Comment by gregpabian** [comment]
It wasn't a problem with the browser recognition, rather with sorting browsers in table headers.

**Comment by gregpabian** [comment]
Issue still exists.
