### ISSUE TITLE
Show tests status in the window title

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#180]
There's a problem with running tests on IEs that you can't see the status, because tests are run in new windows (tabs). So for instance you can't stop tests after first errors. Personally, after making some changes that might affect the entire code base I run all tests, but if it doesn't look promising, I stop the tests run and investigate what was wrong. This I cannot do with Bender on IE.

Showing tests results in the title will solve this problem.

**Comment by adelura** [comment]
Cool one :)
