### ISSUE TITLE
[Jobs] Add indication of success or failure in job view

### ISSUE THREAD

**Issue by jodator** [benderjs/benderjs#187]
On a job view there is no job summary so you have to scroll through all the item to check if job was successful or not. There should be such indication for whole job. Such status is displayed on jobs list view.

This is annoying especially when running the job again from job view. If there are many test cases you cannot tell at first look if all test are green or not.

**Comment by gregpabian** [comment]
Sounds cool, we could add a summary result for each browser at the top of the results table.
