### ISSUE TITLE
Jobs without snapshots should be kept in sync with tests code base

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#191]
I create jobs without snapshots while working on tests with code coverage. This means that I create a job once and run it from time to time to check code coverage status.

The problem I encountered is that this job is not kept in sync with the tests I'm working on.

1. New test file which matches the query that I used when creating a job, is not automatically added to the job.
2. AFAICouldSee job has hardcoded values of Bender's meta comments. It means that when I add a new plugin or include a new file using `/* @bender-* */` comment it does not affect the job (so tests fail). 

These two facts force me to create new job every time one of these two things change (which is pretty often). That's not useful. It would be great if jobs without snapshots were really up to date with the code base.

**Comment by gregpabian** [comment]
Ad 1. Of course it's not added - what do you expect? That Bender will watch the file system whole the time and recreate all job related items in the databases on every file changed? There's too much stuff going on when creating a job to have it happening that often - scan the test paths, filter found tests, insert them into one database, create tasks for all browsers specified in the job and put them into another database. Besides, we already had tons of problems with file watchers and finally dropped them.

So I wouldn't implement any "automatic" behavior for this purpose, but we can add a "recreate" button or force job's recreation when it's restarted.

Ad 2. Yes, I do this on purpose, simply, to speed up things. Having to collect all the test's metadata each time would be just a huge waste of time. Again, adding the "job recreate" feature would help solve this part.

**Comment by pjasiun** [comment]
> So I wouldn't implement any "automatic" behavior for this purpose, but we can add a "recreate" button or force job's recreation when it's restarted.

:+1

**Comment by Reinmar** [comment]
> Of course it's not added - what do you expect?

I don't know the internals. I could for example expect that when snapshot is not created Bender creates instrumented files on the fly, when requested (it might even cache them, but would need to invalidate cache if date has changed). Or anything similar. It's not apparent from outside that creating a job requires  hard-caching everything.

In other words - the option is called "no snapshot". As we can see some partial snapshot is created. It means that this option does not do what it says.

**Comment by Reinmar** [comment]
> So I wouldn't implement any "automatic" behavior for this purpose, but we can add a "recreate" button or force job's recreation when it's restarted.

Can the job be recreated on every restart? That would be a solution to all this.

**Comment by scofalik** [comment]
I pushed branch t/191 where I implemented that solution. Will be available on dev and then on master soon :)
