### ISSUE TITLE
Filter suggestion shows always all options

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#192]
If I add to the bender tests filter (on the dashboard) `is:manual` it would be useful if adding next criterion I get only manual tests in the list of suggestions. Generally speaking in the suggestion box should be no items which will return no tests if they would be added to the current criteria.

**Comment by gregpabian** [comment]
As we agreed, it will make sense to reduce number of options after applying one of `is:` filters.

**Comment by gregpabian** [comment]
Resolved with #219
