### ISSUE TITLE
No useful data on the list of jobs.

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#194]
A the moment what I see on the list of jobs is:
 - ID - who actual need this? I know only one guy who could remember jobs by the ID (@adelura).
 - Description - I think that if the job has description it should be used instead of ID, so there will be more space for it.
 - Created - this is useless for me, but I can understand it could be useful for someone else, however "Created" should be smaller or available only on the job page,
 - browsers/results - that is cool (however it is not the most important information).
![screenshot from 2015-03-25 12 40 37](https://cloud.githubusercontent.com/assets/1166967/6823832/440b2d92-d2ec-11e4-9806-455f0b8230e8.png)

What is the most important information for me is the list of "Filters" used to create a Job. Having it I actually do not need descriptions.

The perfect Jobs Dashboard would be: list of the "Filters" with the smaller description bellow (if available), and "Results" on the right.

**Comment by gregpabian** [comment]
I won't agree that a filter is the most important information. A description is also important, especially when we talk about a job with a snapshot taken -then a description may tell what's the version of the code we took a snapshot of. Having filters could be useful, but the list may immediately got bloated with information.

Job ID will also become an important information when the command line for jobs is ready. (#60)

I think everyone has it's one opinion on what's important and what's not - the only reasonable solution would be to have the fields in the list configurable, but again, we do this for all lists or none of them to have the UX consistent.

**Comment by jodator** [comment]
I think that current list is ok. Browsers list looks poor on screenshot but it make sense when more browsers are added to the job so you can see on which browser the job fail.

**Comment by scofalik** [comment]
I pushed branch t/194 with a fix proposal. I put description and ID together and ID is now shown when description is not available. Created cell is smaller and in the saved place I put filter column. I tested on my laptop with resolution width 1366px.

When you add all browsers to the results you still easily can have 4 visible tags.

![table](https://cloud.githubusercontent.com/assets/1502228/9383747/9b3dff9e-474b-11e5-8c38-60a0ac4ffa83.PNG).

Tell me what you think about it.

**Comment by jodator** [comment]
Look nice :+1:

**Comment by pjasiun** [comment]
Great! :+1:

**Comment by mlewand** [comment]
Lookin good! :+1:

**Comment by scofalik** [comment]
Okay so I will merge it with dev.
