### ISSUE TITLE
Prevent from accidental closing window with running tests

### ISSUE THREAD

**Issue by adelura** [benderjs/benderjs#201]
If tests are running there should be an confirm popup on dashboard which will ask whether you want to close a page.

**Comment by Reinmar** [comment]
Heh... could be useful :D.

**Comment by pjasiun** [comment]
+1

**Comment by mlewand** [comment]
Why didn't we thinkg about it earlier? : D Good idea! :+1:

**Comment by gregpabian** [comment]
+1
