### ISSUE TITLE
Introduce benderjs-promise

### ISSUE THREAD

**Issue by fredck** [benderjs/benderjs#202]
In CKEditor 5 we assume that compatible browsers will provide `Promise` natively. That's true for most cases, but [PhamtonJS doesn't have Promise](https://github.com/ariya/phantomjs/issues/12401) yet. Therefore, it is not possible to run CKEditor 5 tests headlessly with PhantomJS.

A new plugin should be available for Bender.js (benderjs-promise) which would automatically inject a [ES6 Promise polyfill](https://www.npmjs.com/package/es6-promise) into browsers that don't provide it.

**Comment by gregpabian** [comment]
I tried to use the library you suggested, but thanks to this line: https://github.com/jakearchibald/es6-promise/blob/master/dist/es6-promise.js#L948 we'll face the same problem as usual when using along with benderjs-amd - anonymous define... I'll try to find an alternative library for that purpose.

**Comment by gregpabian** [comment]
The plugin is ready and published, see: [benderjs/benderjs-promise](https://github.com/benderjs/benderjs-promise).
I tested it with CKEditor5 and PhantomJS and it works just fine. If you have any issues with it, please report them in the plugin's repository.
