### ISSUE TITLE
Include `phantomjs` as a Bender dependency

### ISSUE THREAD

**Issue by fredck** [benderjs/benderjs#205]
Calling `bender run` should work out of the box but it doesn't because it uses PhantomJS and if it is not installed it throws an error.

PhantomJS is not a browser like others. One doesn't use it for browsing for real. It's actually a tool for applications like Bender, so it makes sense having it together with Bender. Therefore `phantomjs` should be added to the dependency list.

**Comment by Reinmar** [comment]
I'm not sure if it should be a default dependency. In CKE4 we don't use `bender run` at all, so why should we wait for Phantom to install? I'm also unsure if it won't cause some compatibility issues - could it happen that on some platform Phantom is not supported so the whole Bender installation fails?

Instead, I would only force people to install Phantom when it's needed - so when they use `bender run`. Just like now you would need to install it manually. So the only thing that might need to be improved is the error that you have when it's not available.

**Comment by jodator** [comment]
I have similar feelings about that as @Reinmar. Also i think that you can install PhantomJS globally.

**Comment by gregpabian** [comment]
Yeah, I wouldn't make it a direct dependency as well - it's takes over 50MB to install a thing that might never be used. Besides, I'm don't think that browser-launcher could recognize a local installation of PhantomJS (in fact, I'm pretty sure it won't). So my suggestion would be rather removing the default launch browser configuration completely and just dropping a message when someone wants to execute `bender run` without having a launch browser defined in `bender.js` file (or passing it with -b option).

**Comment by Reinmar** [comment]
+1.

Additional argument - we are often forced to check something in the commits history. It works fine most of the time before restarting Bender because the tests API didn't change that much, but sometimes we need to downgrade Bender. The bigger the installation, the bigger pain it will be.

**Comment by pjasiun** [comment]
And we install bender for every preset and rebuild it every time we rebuild preset for testing. Even now installing bender is the most time consuming part of rebuilding presets for testing.

**Comment by fredck** [comment]
Well, the current benderjs folder in node_modules is already a 100MB+ beast, so I would not be worried about sizes... it's more about convenience.

Additionally, installing phantomjs for me wasn't so slow... way much better than the current installation of bower performed when installing benderjs.

I think we should not change current defaults for `bender run`, but a better message should definitely be displayed and, in the case of PhantomJS, it should have a quick help on how to install it globally (a copy/paste for the npm call).

I think we're just not used to use `bender run`... but really it runs test so much faster that once we'll reach the 3000+ tests, it should be a best practice to use this to run tests during development or during review.

**Comment by scofalik** [comment]
Do we have a consesus about this? It seems that we all agree that this issue should be left and closed. I changed message to a more insightful one in other issue.

**Comment by fredck** [comment]
At least for now, it is agreed to not have it.
