### ISSUE TITLE
Test summary in job view is wrong when scrolled.

### ISSUE THREAD

**Issue by jodator** [benderjs/benderjs#210]
Scroll:
![bender_scroll](https://cloud.githubusercontent.com/assets/247363/7181083/075798f0-e448-11e4-987a-5f9e9c3d755c.png)

Not scrolled:
![bender_no_scroll](https://cloud.githubusercontent.com/assets/247363/7181087/08a2fe98-e448-11e4-9e60-31e361b754c9.png)

The job was restarted using restart job button.

**Comment by gregpabian** [comment]
Note to self: update the contents of the "fixed header" every time the results are updated :wink:
