### ISSUE TITLE
Show exceptions in the console when running from dashboard

### ISSUE THREAD

**Issue by mlewand** [benderjs/benderjs#213]
Currently no information is logged to the console when tests are ran from dashboard and assertion fails.

At the beginning I thought it's a regression that exception failing the TC are not put into the console. But later it turned out that there has been introduced a feature that will show the exception after clicking status column (in a proper test suite row).

![Screenshot](http://i.imgur.com/LEFSqhv.png)

## Problems

* It's counter-intuitive, there's no indication whatsoever that it is clickable.
* It's good for a lot of exceptions, but it's worse if only few tests are failing.

### Better Indication

We should do a better indication that status is clickable. I know that underline would look crappy, but how about some icon or sth?

### Errors in Console

We should put the console as well. It might be as simple as calling `console.error`, but we need to put something. Devs are used to look for errors in console, and it was actually the first reaction when I asked today where do I find failed assertions when running the tests from dashboard.

**Comment by gregpabian** [comment]
> it turned out that there has been introduced a feature that will show the exception after clicking status column (in a proper test suite row).

It's there since Bender 0.1.14, so no that new... :trollface: 

> We should do a better indication that status is clickable. I know that underline would look crappy, but how about some icon or sth?

I don't think another icon would help, there's already one (sometimes even two), the "crappy" underline would be enough I guess.

> We should put the console as well.

We could do this, but we have to pass the information what tests throws the error, otherwise it would be useless.
