### ISSUE TITLE
Test Bender's compatibility with Node 0.12.x

### ISSUE THREAD

**Issue by gregpabian** [benderjs/benderjs#214]
The latest Node.js version is 0.12.2 but at the moment we test Bender against Node 0.10.x and 0.11.x only. We should test Bender for Node 0.12.x and eventually update the configuration for Travis CI.

**Comment by scofalik** [comment]
I already use Bender.js on Node 0.12.7 and 0.12.x is added in Travis config file and is used by Travis.
