### ISSUE TITLE
Get rid of "regressions" feature

### ISSUE THREAD

**Issue by gregpabian** [benderjs/benderjs#215]
The name of the feature is misleading, also it adds a lot of logic to each framework adapter, while almost every testing framework introduces some simple methods to ignore test cases.

**Comment by scofalik** [comment]
Removed from adapters:
https://github.com/benderjs/benderjs-mocha/commit/cb7d17d3bb4b1c88ced01d642c2a00e5b4d9afc4
https://github.com/benderjs/benderjs-jasmine/commit/2514a54e6310131d25c398f7b90a83f6fd9c0138
https://github.com/benderjs/benderjs-yui/commit/1a616b30c03fcbb45077fd7431eab5874d8f2fec
https://github.com/benderjs/benderjs-qunit/commit/3aa741bb26a9eff20d1aeafecbf5f86090e14c96

And from the Bender.js core.

**Comment by gregpabian** [comment]
:+1:
:trollface:
