### ISSUE TITLE
Add git hook which will prevent from commiting code with style and other issues.

### ISSUE THREAD

**Issue by adelura** [benderjs/benderjs#226]
We should pick solution from [boilerplate](https://github.com/ckeditor/ckeditor-boilerplate).

**Comment by scofalik** [comment]
Using Grunt just to create git hooks is an overkill. Right now, Bender.js does not use Grunt so I see no reason introducing it. We can use already existing mechanisms:
* we store hooks in git repository (directory `./hooks`),
* in `postinstall` script we add copying hooks from `./hooks` to `./.git/hooks`,
* `pre-commit` hook runs `npm run-script lint` which is already declared.

So right now, after pulling the repository and running `npm install` we will have git hooks ready.
