### ISSUE TITLE
No phantomjs error could be better

### ISSUE THREAD

**Issue by pjasiun** [benderjs/benderjs#228]
When I run `bender run` I get this message:
```
> bender run
info: [plugins] Loaded plugin: benderjs-amd
info: [plugins] Loaded plugin: benderjs-mocha
info: [plugins] Loaded plugin: benderjs-chai
info: Bender.js v0.2.3 Server started at http://localhost:1030
info: [socket-io] socket.io started
info: [socket-io] handshake authorized uAGlTVcRIBJXvwnir-Rk
error: [launcher] no matches for phantomjs/*
```
And I think that for some people it may be not clear that `phantomjs` is not included is the `benderjs` and it needs to be installed separately to use `bender run`. The message should be changed to something more meaningful:
```
info: [launcher] Use phantomjs to launch tests.
error: [launcher] phantomjs is not installed on you system.
```

**Comment by scofalik** [comment]
Fixed with https://github.com/benderjs/browser-launcher2/commit/e7f7cc3fbd8dcacf4e42b2d48b238451984e9d5f

pushed commit bumping up browser-launcher2 version.
