### ISSUE TITLE
Bring support for Microsoft Edge

### ISSUE THREAD

**Issue by oleq** [benderjs/benderjs#232]
We must implement the support for Edge. At the moment Bender does not recognise the browser and it's impossible to include it in a job.
![screen shot 2015-06-12 at 12 28 43](https://cloud.githubusercontent.com/assets/1099479/8128390/9f9eba16-10fe-11e5-9553-2d64ca34df96.png)

**Comment by adelura** [comment]
Related to https://github.com/benderjs/benderjs/issues/179.
