### ISSUE TITLE
Conflict in deps installed by Bower 

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#233]
```
Unable to find a suitable version for underscore, please choose one:
    1) underscore#1.4.4 - 1.6.0 which resolved to 1.6.0 and is required by marionette#2.4.1
    2) underscore#>=1.5.0 which resolved to 1.6.0 and is required by backbone#1.1.2
    3) underscore#>=1.3.3 <=1.7.0 which resolved to 1.7.0 and is required by backbone.wreqr#1.3.2
    4) underscore#>=1.7.0 which resolved to 1.7.0 and is required by backbone#1.2.0
    5) underscore#>=1.4.0 <=1.8.3 which resolved to 1.8.3 and is required by backbone.babysitter#0.1.7Prefix the choice with ! to persist it to bower.json
```

**Comment by Tade0** [comment]
This seems to be an issue with marionette itself.

Running `bower install` on this file:
```
{
	"name": "marionette-issue",
	"description": "Issue with bower & marionette",
	"license": "MIT",
	"dependencies": {
		"marionette": "~2.4.1"
	}
}
```

Yields the same dialog.

Related issues:
https://github.com/marionettejs/backbone.marionette/issues/2446
https://github.com/marionettejs/backbone.marionette/issues/2230

According to this comment:
https://github.com/marionettejs/backbone.marionette/issues/2446#issuecomment-112083212
Underscore is scheduled for update in Marionette 2.4.2 to version 1.8.3.

**Comment by scofalik** [comment]
Linked issues are already closed. It seems that the problem is not occurring anymore.
