### ISSUE TITLE
Broken test file does not affect tests status

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#234]
I can have 100% green even though one test file is completely broken.

Related to #211.

**Comment by scofalik** [comment]
This is not a bug. Percentage counter shows how many tests completed (either with failure or success as a resuly) compared to total number of tests.

**Comment by Reinmar** [comment]
Right. Then we need some other indication of failures in one of the test files. Will you report a ticket for this?

**Comment by scofalik** [comment]
These tests are red on list and since 59282713323 they will be also included in failure counter. I haven't made a ticket for this.

**Comment by Reinmar** [comment]
+1. Thanks.
