### ISSUE TITLE
Some scripts are not loaded

### ISSUE THREAD

**Issue by Tade0** [benderjs/benderjs#235]
When running tests for CKEditor using Bender on dev branch I get 100% failure rate.

The problem seems to be that some scripts are not loaded.

view-source of a specific test (e.g. http://tests.ckeditor.dev:1030/tests/core/ckeditor/addcss ) shows:

```
[...]
<meta charset="UTF-8">
	<title>tests/core/ckeditor/addcss</title>
	<script src="/js/bender-config.js"></script>
	<script src="/js/env.js"></script>
	<script src="/js/client.js"></script>
<script>
[...]
```
Instead of:
```
[...]
<meta charset="UTF-8">
	<title>tests/core/ckeditor/addcss</title>
	<script src="/js/bender-config.js"></script>
	<script src="/js/env.js"></script>
	<script src="/js/client.js"></script>
<script src="/apps/ckeditor/ckeditor.js"></script><script src="/plugins/home/tadeo/Documents/repos/benderjs-yui/vendor/yui-3.16.0-test.min.js"></script><script src="/plugins/home/tadeo/Documents/repos/benderjs-yui/lib/adapter.js"></script>
[...]
```

`git bisect` indicates that this commit:
https://github.com/benderjs/benderjs/commits/0047af21551dce7ed9904ce3ea1488e4c3a23aae
introduces the bug.

**Comment by Reinmar** [comment]
The dev branch may not be yet compatible with all existing Bender plugins so it should not be used for normal work.

But good that you caught it before we released 1.0.0. We will need to update plugins or fix Bender.
