### ISSUE TITLE
Filtering by test name stopped working

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#244]
1. Open http://tests.ckeditor.dev:1030/tests/core/editable/keystrokes/delbackspacequirks/collapsed#tests%2Fcore%2Feditable%2Fkeystrokes%2Fdelbackspacequirks%2Fcollapsed%20test%20backspace%2C%20merge%20%232

Expected: Only one test should be run.

Actual: You can see all tests.

**Comment by Reinmar** [comment]
Interestingly, the same works fine in CKE5, so it may be a bug in benderjs-yui.

**Comment by scofalik** [comment]
It is a bug in benderjs-yui. I though I already fixed in in last patch for that project https://github.com/benderjs/benderjs-yui/commit/3519e3a20b3d3828747f40fce2656c54e46c9f79 but maybe it wasn't enough.

**Comment by scofalik** [comment]
This issue should be finally fixed with https://github.com/benderjs/benderjs-yui/commit/06127d4091ef72a616312a09735b22094d493c0c .
