### ISSUE TITLE
Expose Socket.io to plugins.

### ISSUE THREAD

**Issue by jodator** [benderjs/benderjs#254]
It would be beneficial to expose socket.io so benderJS front-end plugins could communicate with back-end counterpart.

**Comment by Reinmar** [comment]
What is a real use case for exposing socket.io to FE env? It will affect tests performance (as loading any additional script does), so this should be clear that we need this.

**Comment by jodator** [comment]
Example use case: create docker integration for bender.

I have a plugin that exposes docker API for front-end scripts so tests are able to start/stop docker-machine and execute some docker-compose comands like up, down, build.

In order to acheve this I have server-side component that listens on `/docker` socket.io channel and executes commands on back-end.

Above setup allows to create automated integration tests using bender as test runner.
