### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#45]
This is an umbrella ticket for the performance issues.

There are two types of problems:

1. A general tests execution performance. It's not bad, but it's worse than CKTester's. So if there's a way to improve it, we should try. This is a more long-term issue - we can gradually work on it.
2. IE8's problems with dashboard. This is an important problem now, because it takes >5s to load dashboard.

Steps:

1. We need to identify what causes issues on IE8.
2. Bender's (and its plugins') JS files loaded in every test file could be concatenated.
3. We need to identify processes that are slower in Bender than in CKTester. Is it test file loading, iframe creation or communication with it, slower static files server, broken static files caching?

**Comment by gregpabian** [comment]
It's been over 6 months from the last update in this thread and no new performance issues reported since then. I'm going to close this one - if anything new related to the performance appears, please open a new ticket for that.
