### ISSUE TITLE
Keep table headers fixed

### ISSUE THREAD

**Issue by gregpabian** [benderjs/benderjs#65]
Table headers should be visible while scrolling the table.

**Comment by gregpabian** [comment]
Works an all browsers including IE, but on IE there's a moment you can see the header moving to it's position. Not sure if and how to fix it though... Let's get back to this if it becomes a real issue.

**Comment by Reinmar** [comment]
Does it cause some slowdown on IE8? If so, I would disable it on IE8,
because the dashboard is already a bit slow there.

On Mon, Mar 30, 2015 at 11:17 AM, Grzegorz Pabian <notifications@github.com>
wrote:

> Works an all browsers including IE, but on IE there's a moment you can see
> the header moving to it's position. Not sure if and how to fix it though...
> Let's get back to this if it becomes a real issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benderjs/benderjs/issues/65#issuecomment-87606589>.
>



-- 
Piotrek Koszuliński,
http://twitter.com/reinmarpl

**Comment by gregpabian** [comment]
Not really, there's no noticeable slowdown on IE8, what's even more surprising this "moving" effect I mentioned is barely visible on IE8, while quite noticeable on IE9 and 11.
